version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql_data:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: flask_app
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    command: flask run --host=0.0.0.0 --port=5000

volumes:
  mysql_data: